        {view === 'reports' && (
          <ReportsView
            darkMode={darkMode}
            currentDate={currentDate}
            currentMonthTransactions={currentMonthTransactions}
            transactions={transactions}
            scheduled={scheduled}
            categories={categories}
            last6MonthsData={last6MonthsData}
            reportFilter={reportFilter}
            setReportFilter={setReportFilter}
            reportChart={reportChart}
            setReportChart={setReportChart}
            formatCurrency={formatCurrency}
            showVal={showVal}
            handleExportPDF={handleExportPDF}
            handleExportExcel={handleExportExcel}
            setHighlightedCategory={setHighlightedCategory}
            setFilterType={setFilterType}
            setView={setView}
          />
        )}
